### PR TITLE
Work around #177

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by pcuzner** [comment]
I don't fully understand the options open to us with this problem. @b-ranto can you please take a look, linking out to a personal repo just feels wrong here

**Comment by zmc** [comment]
@pcuzner I should have mentioned that we only need this until the next release of testinfra. We can either merge and revert later, or I can continue to test by merging this branch with master (plus any relevant WIPs) as I have been.

**Comment by b-ranto** [comment]
@zmc Could you force a version of testinfra in the tox.ini file instead of relying on your own repo?

**Comment by zmc** [comment]
@b-ranto there's no version to force, since it hasn't been released yet.

**Pull request merged**
