### PR TITLE
ceph-collectd: Only set SEL context on filestore

### PR DESCRIPTION
**Pull request by zmc**
The file doesn't exist with bluestore.

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by pcuzner** [comment]
By bypassing bluestore, won't selinux+bluestore cause the collector to fail. Should the fix incorporate the naming of the bluestore drives, or include a separate task that does the same thing for bluestore?

**Comment by zmc** [comment]
I can't tell you either way if there are issues with SELinux and bluestore. We're only running restorecon on the journal specifically, though, which isn't relevant for bluestore, is it?

**Comment by pcuzner** [comment]
Yep, the selinux policy ensures the osd collector has access to the "journal" link through the ceph_var_lib_t selinux context. However, if it's bluestore the code will check if the block.wal file exists and if so attempt a readlink - if selinux context is not right the collector will fail. Now block.wal is optional, so it's possible that this hasn't been hit yet.

see https://github.com/ceph/cephmetrics/blob/master/collectors/osd.py#L223

**Comment by zmc** [comment]
ok. Does that mean that instead of skipping the task for bluestore, we attempt a restorecon on block.wal?

**Comment by zmc** [comment]
Testing a new approach: http://pulpito.front.sepia.ceph.com/zack-2018-05-16_23:11:37-cephmetrics-master-distro-basic-ovh/

**Comment by M0les** [comment]
FWIW, Currently RHEL 7.5 Ceph-3 doesn't have this fix as far as I can see. I don't know when RedHat might integrate it, so a hack-around I've been using is to issue on all the Ceph nodes: `for osd in /var/lib/ceph/osd/ceph-*; do ln -s ${osd}/journal ${osd}/journal; done` prior to running the cephmetrics-ansible playbook.

**Pull request merged**
