### PR TITLE
Add a couple of packaging changes

### PR DESCRIPTION
**Pull request by b-ranto**

### CODE REVIEW

**Comment by b-ranto** [comment]
@zmc @pcuzner please comment/review. I was able to build the packages with the spec file, once we merge I can do a jenkins build.

**Comment by zmc** [comment]
I don't think we can just delete this ansible code; we'll still want to be able to deploy without packages. I can help with ansible that supports both use-cases.

**Comment by b-ranto** [comment]
btw: this is ~integrated with a jenkins build job as in https://github.com/ceph/ceph-build/pull/748 so there can be consumable upstream builds for this soon. Personally, I am not sure it is worth the effort to keep having both options in the ansible code but I am not against it.

**Comment by b-ranto** [comment]
The upstream build worked:

https://shaman.ceph.com/repos/cephmetrics/wip-packaging/30822401932f1aad5c45698e814dbf2667826a1a/default/34950/

**Comment by zmc** [comment]
@b-ranto I just filed a PR that should cover the necessary ansible changes. Perhaps you could file one with just the spec file?

**Comment by b-ranto** [comment]
ok, I dropped most of the ansible changes (I only kept the path rename for /usr/lib64/collectd/python-plugins -> cephmetrics) which your PR does not cover.

**Comment by b-ranto** [comment]
I rebased on top of the Zack's ansible changes and added a couple of ansible-related commits (limited setup_repo actions to devel mode and unified the location of cephmetrics collectors).

**Comment by b-ranto** [comment]
You can this repo on top of epel to test my grafana/cephmetrics packages https://copr.fedorainfracloud.org/coprs/branto/cephmetrics/repo/epel-7/branto-cephmetrics-epel-7.repo

**Pull request merged**
