### PR TITLE
ansible: Document variables

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by pcuzner** [comment]
What's a devel_mode deployment, and how does it differ from production? Maybe worth adding that in the text?

**Comment by zmc** [comment]
@pcuzner I agree we need more clarification here. Would you be ok with me expanding on that later when more of the production mode is implemented?

**Comment by pcuzner** [comment]
Sure

**Comment by wusui** [comment]
I have a production mode deployment doc first pass in wip-metrics-wusui pushed to origin.  The changes were made to README.md

**Pull request merged**
