### PR TITLE
Enable prometheus

### PR DESCRIPTION
**Pull request by b-ranto**
This patchset will enable prometheus as an optional cephmetrics backend. It still uses graphite as a default backend and for events even in prometheus mode.

The patchset is set to be compatible with prometheus 2.0+.

The prometheus dashboards are handled as a minimal set of changes necessary to patch the graphite dashboards. The basic compatibility between dashboards is handled by build scripts (the builds will fail if the dashboards are not compatible).

### CODE REVIEW

**Comment by jcsp** [comment]
So using collectd here means that there aren't any meaningful labels on the time series, right?  That seems like a major issue to me.

What's the motivation for using collectd rather than the ceph-mgr prometheus plugin and/or the ceph exporter?  If there's a scale concern then this would be a good time to do the (minor) work to harmonize the series names/labelling between those two tools, and get the central stuff from ceph-mgr and the per-OSD bits from the ceph exporter on nodes.

Keeping Graphite around seems kind of gratuitous here: I'm not sure many users would be enthusiastic about running Graphite *and* Prometheus, it's more of an either-or.

**Comment by b-ranto** [comment]
@jcsp This is just the first iteration on the way to the complete prometheus enablement. If we try to do everything at one shot, we might never get there. The aim here is not to break anything, at least not yet. For that we need collectd as well as graphite (prometheus does not support events on its own, we are looking at other ways to implement events though).

As for the use of collectd instead of ceph-mgr prometheus plugin. I looked at the plugin and iirc it would break things. For instance, in cephmetrics we are often interested in per node data but the plugin does not provide you with that kind information since it groups the statistics by osd/mon/..., not the node. We want to use the plugin in the future, though.

btw: I managed to sanitize the labels a bit by playing with the prometheus config so I no longer need to do a ton of label_replace calls. We might be able to sanitize it even further if we played with the prometheus config a bit more.

**Comment by jcsp** [comment]
> For instance, in cephmetrics we are often interested in per node data but the plugin does not provide you with that kind information since it groups the statistics by osd/mon/..., not the node.

It is meant to be possible to get a per-node view by using the labels on the OSD's metadata series.  Can you start a mailing list thread or open a ticket about what you've tried, so that we can see if there's extra output that's needed?

Getting the schema/labelling right first time is essential -- if we ship something that uses collectd/graphite style labels, then switching later to something that uses properly labelled output will involve dropping the history and rewriting any dashboards consuming it.  Going from graphite to prometheus is intrinsically a breaking change (i.e. drop all history), so the important thing is to get all the changes we want into that one breaking change, rather than intending to make more later.

**Comment by b-ranto** [comment]
@jcsp We do not want to drop all history with prometheus, the plan is to find a way to migrate existing data from graphite to prometheus for already running instances. This will be easier done with the collectd exporters.

Even if/when this gets merged it does not mean it will be the final way we will do it, we still have a couple of months to figure the rest out before the next release. This is mostly initial work to get prometheus enabled, get some basic testing, etc.

Regarding the missing per-node view: IIRC (I might be wrong, it was quite a while since I was looking at it), I did not find a way to identify what OSDs were running on what hosts for some statstics (you were just told that a certain statistic is for a certain osd.<num> and there was no information about the node running the osd in the metric). I would have to take a look again to be more sure/specific about it.

**Comment by b-ranto** [comment]
Closing in favour of #160.

**Pull request closed without merging**
