### PR TITLE
Finalize packaging changes

### PR DESCRIPTION
**Pull request by b-ranto**
We need to disable devel_mode in the RPMs for https://bugzilla.redhat.com/show_bug.cgi?id=1494260

For this, we need to fix merge_vars.yml so that it does not reset values to empty strings.

### CODE REVIEW

**Comment by b-ranto** [comment]
FYI: This branch was tagged (no annotated tags, yet, I guess we can continue doing rebaseswith a moving v1.0 tag until a final release), tested and built downstream. The packages should be available in the next compose.

**Comment by b-ranto** [comment]
I had to add one more commit. The ipaddr ansible filter that we used in one of the recent commits requires python-netaddr for it to work.

**Comment by zmc** [comment]
Thanks for this @b-ranto! Do you think we could keep patches in a subdirectory?

**Comment by b-ranto** [comment]
I was thinking along the same lines and I wanted to put it in the dist/ folder but that wouldn't work as we are removing that directory during the jenkins build to make sure it is clean. :-/

Any ideas where to put it?

**Comment by zmc** [comment]
@b-ranto perhaps `./patches/` ?

**Comment by b-ranto** [comment]
FYI: I have pushed the patch that moves the patch off the gitroot to the patches subdirectory.

**Pull request merged**
