### PR TITLE
Restart Grafana immediately after .ini update

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
A cleaner way of implementing 2a6f76d

**Comment by b-ranto** [comment]
ok, but that is still not enough, it takes a while for grafana to actually start listening on the port (I got connection refused if I did not wait for port 3000).

**Comment by zmc** [comment]
Oh, I hadn't seen that before. I can add a "wait for port" task as well.

**Comment by b-ranto** [comment]
That still might not be enough. I did stop the service (and waited for
it to be stopped) on purpose. It was the only way to actually make sure
the service was started with a fresh config. The restart command might
be async as well -- i.e. it can just send a signal to the daemon and it
may take a while for the daemon to restart, you could still be getting
the old daemon running if you restart even if you wait for the port
(the old instance could still be handling the restart signal).

This implementation was the safest and definitely the most stable out
of all the options I have tried.

**Comment by zmc** [comment]
Ouch. Okay, let's go with your changes then.

**Pull request closed without merging**
