### PR TITLE
ansible: Build and install SELinux module

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
This should address https://github.com/ceph/cephmetrics/issues/30

**Comment by zmc** [comment]
Yeah, `checkmodule` was reporting an error that, when I investigated, seemed to be solved by using this `Makefile` instead. Worked like a charm :)

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
@pcuzner I had to make a change to appease the linter; could you re-approve if it still looks good? Thanks!

**Comment by mbukatov** [comment]
Wouldn't be better to solve this by shipping the policy in rpm package?

**Comment by b-ranto** [comment]
It is shipped in rpm package, this is for devel deployment.

**Comment by pcuzner** [comment]
@b-ranto It's not the build process I'm concerned about - it's installing make everywhere. I used to work for Banks, and having tools like that installed on prod machines was a definite no-no - security teams would block that kind of thing. That's what I was querying.

**Comment by b-ranto** [comment]
@pcuzner Banks will (hopefully) use the rpm packages and there is no runtime dependency on make for that (the policy is built when the rpms are built), this is only for devel deployment with ansible.

**Pull request merged**
