### PR TITLE
Collect more pool stats, and display capacity in dashboard

### PR DESCRIPTION
**Pull request by zmc**
https://github.com/ceph/cephmetrics/issues/104

### CODE REVIEW

**Comment by zmc** [comment]
@pcuzner Took me a while to figure out the best way to make dashboard changes. What I'm doing is:
1. Adding the panel in the UI
2. Exporting just the panel's JSON
3. Loading the panel and existing dashboard from the git repo into Python objects
4. Appending the panel to the appropriate row in the dashboard object
5. Making the necessary adjustments to each panel's span
6. Dumping the object back out to disk

I've added an alert now as well, but [`dashUpdater.py` refuses to update `alert-status`](https://github.com/ceph/cephmetrics/blob/6ba1e883d14db515dbc008285ceb96bd96c3fe6d/dashUpdater.py#L381-L384).

**Comment by pcuzner** [comment]
@zmc That process would work.

The way I do it is over the api (which is what dashUpdater uses)
1. Update the dashboard with the new element
2. export the dashboard via the api
e.g.
curl -u admin@localhost:admin -H "Content-Type: application/json" -X GET http://localhost:3000/api/dashboards/db/ceph-backend-storage -o ceph-backend-storage-raw.json

3. json_pp the json
4. push to github

**Comment by zmc** [comment]
@pcuzner I've updated again. I have a working alert that gets templated properly; I've removed the old broken alert from the pools dashboard; and I've replaced the line graph with a table under the 'top 5' section. I did look at using bar graphs, but I decided against it because:

1. Using a small graph in the overview row looked horrible as the labels just didn't fit properly in this case, and we only have a small number of pools
2. Using a larger graph in its own row would more or less feel like a waste of space compared to a compact table
3. If we want a more visual representation of pool capacity, what I'd suggest is putting a graph in the per-pool rows. I'm not sure how helpful that would be, so I didn't do that yet. It would be a quick change though.

screen shot 2017-09-05 at 12 20 07 pm

**Comment by zmc** [comment]
The last commit adds:
screen shot 2017-09-05 at 4 38 37 pm

**Pull request merged**
