### PR TITLE
Dashboard refresh

### PR DESCRIPTION
**Pull request by pcuzner**
dashboard updates reflecting the work done in the demo cluster including refreshes of existing dashboards and new dashboards for iscsi/rgw/mds the cephmetrics host itself.

Also addresses #171, #172 

Large diffs!

### CODE REVIEW

**Comment by zmc** [comment]
I think that anywhere we see:
```
         {
             "id": "prometheus",
-            "name": "Local",
+            "name": "Prometheus",
             "type": "datasource",
-            "version": "1.0.0"
+            "version": "5.0.0"
         },
```

we need to keep using the "Local" name, since that's what we deploy.

**Comment by pcuzner** [comment]
@zmc - will update

**Comment by pcuzner** [comment]
@zmc source name updated

**Comment by zmc** [comment]
@pcuzner this conflicts with master because of `cephmetrics-host.json`; how should we handle that?

**Comment by zmc** [comment]
@pcuzner apologies; we need one more change here.

I just discovered that Grafana 5.1.x will fail to update dashboards if there is a conflict with the `uid` field. In my testing, things work properly with that field omitted from all of the dashboards.

**Comment by pcuzner** [comment]
OK will push updates tomorrow for uid, and the inclusion of ceph_pg_unknown stats on at-a-glance and ceph-health panels

**Pull request merged**
