### PR TITLE
DNM: Reorganizing things for testability

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by zmc** [comment]
@pcuzner I've just pushed changes that address what we talked about yesterday. I'm going to start working on proper packaging as well, but I might not finish it in time to put it in this PR.

**Comment by pcuzner** [comment]
I think I would have preferred to have the ceph class outside of init.py...and just have ceph as a module in the collectors. Having the class in init means every import gets from cephmetrics gets the class, but it's not a shared component across all modules - so I don't think it should be there.

I've added @GregMeno as the tie-break on the use of init.py :)

**Comment by zmc** [comment]
I'm confused - what's the concern here exactly? On import, a class is defined - not instantiated - and no other code is executed.

I suppose we could move the definition to another module, but we'd still want to import it from `__init__.py` anyway, I think...

**Comment by pcuzner** [comment]
The concern is the same as yesterday. To my mind, init.py is the place for shared state, or package configuration and used by exception, rather than like this. I'm a fan of keeping it simple - I'd prefer to see the ceph class in it's own module (tbh that's what I thought you were going to do)

Not sure what you mean about the need to import from init.py...with the Ceph class in a separate module (ceph.py), cephmetrics,py (the plugin) would just "from cephmetrics_collectors import ceph" and then instantiate as you have for the others with ceph.Ceph()...or you could import the classes within init.py and then for cephmetrics.py "from cephmetrics_collectors" import Ceph...which may be more readable and protect against any future restructure?

**Comment by GregMeno** [comment]
Let's focus on getting the v1.X release features done and agree on then agree on the approach we're taking to improve test-ability

**Comment by GregMeno** [comment]
Let's focus on getting the v1.x release features done and then get agreement on improving testability

**Comment by zmc** [comment]
@pcuzner sorry for yet another misunderstanding about this; it feels like purely a matter of taste but in the interest of getting things done I'll move it to a separate module.

**Pull request closed without merging**
